### ISSUE TITLE
Planページに修正が必要

### ISSUE THREAD

**Issue by katsu-crypto** [katkatprog/pdcaApp#104]
・「この周の目標」の隣のボタンが近い
・目標は灰色でなく黒文字が良い
・前roundの伸長案、改善案を表示する機能が未実装

**Comment by katsu-crypto** [comment]
fix_plan_pageというブランチで作業します

**Comment by katkatprog** [comment]
追加でお願いします
・"期限: "という箇所、カレンダーのアイコンにし、ホバーすると"期限"という吹き出しが出るようにして欲しい

**Comment by katsu-crypto** [comment]
追加でお願いします
・"この周の目標"ではなく、"目標(現時点)"としてください

**Comment by katkatprog** [comment]
追加でお願いします
・"この周の目標"ではなく、"目標(現時点)"としてください

**Comment by katkatprog** [comment]
> ・「この周の目標」の隣のボタンが近い ・目標は灰色でなく黒文字が良い ・前roundの伸長案、改善案を表示する機能が未実装

前roundの伸長案~~というのを実装するために、RoundInfoデータに自己結合させる必要がある

**Comment by katkatprog** [comment]
プルリク出しました。レビューお願いします。

**Comment by katsu-crypto** [comment]
プルリク出しました、レビューお願いします。

**Comment by katkatprog** [comment]
対応ありがとうございました。クローズします
